# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(685, 48)
        Dialog.setStyleSheet("background-color: rgb(216, 225, 229);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(41, 96, 115);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.create_in_line = QtWidgets.QLineEdit(Dialog)
        self.create_in_line.setMinimumSize(QtCore.QSize(0, 30))
        self.create_in_line.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_in_line.setFont(font)
        self.create_in_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(41, 96, 115);")
        self.create_in_line.setObjectName("create_in_line")
        self.horizontalLayout.addWidget(self.create_in_line)
        self.create_tool_button = QtWidgets.QToolButton(Dialog)
        self.create_tool_button.setMaximumSize(QtCore.QSize(30, 30))
        self.create_tool_button.setStyleSheet("color: rgb(41, 96, 115);\n"
"background-color: rgb(173, 197, 207);")
        self.create_tool_button.setObjectName("create_tool_button")
        self.horizontalLayout.addWidget(self.create_tool_button)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(41, 96, 115);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.create_out_line = QtWidgets.QLineEdit(Dialog)
        self.create_out_line.setMinimumSize(QtCore.QSize(0, 30))
        self.create_out_line.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_out_line.setFont(font)
        self.create_out_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(41, 96, 115);")
        self.create_out_line.setObjectName("create_out_line")
        self.horizontalLayout.addWidget(self.create_out_line)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(65, 30))
        self.label_3.setMaximumSize(QtCore.QSize(65, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(41, 96, 115);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.create_name_line = QtWidgets.QLineEdit(Dialog)
        self.create_name_line.setMinimumSize(QtCore.QSize(0, 30))
        self.create_name_line.setMaximumSize(QtCore.QSize(1600000, 30))
        self.create_name_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(41, 96, 115);")
        self.create_name_line.setObjectName("create_name_line")
        self.horizontalLayout.addWidget(self.create_name_line)
        self.create_tool_button_2 = QtWidgets.QToolButton(Dialog)
        self.create_tool_button_2.setMinimumSize(QtCore.QSize(30, 30))
        self.create_tool_button_2.setMaximumSize(QtCore.QSize(30, 30))
        self.create_tool_button_2.setStyleSheet("color: rgb(41, 96, 115);\n"
"background-color: rgb(173, 197, 207);")
        self.create_tool_button_2.setObjectName("create_tool_button_2")
        self.horizontalLayout.addWidget(self.create_tool_button_2)
        self.create_go_button = QtWidgets.QPushButton(Dialog)
        self.create_go_button.setMinimumSize(QtCore.QSize(0, 30))
        self.create_go_button.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.create_go_button.setFont(font)
        self.create_go_button.setStyleSheet("color: rgb(41, 96, 115);\n"
"background-color: rgb(173, 197, 207);")
        self.create_go_button.setObjectName("create_go_button")
        self.horizontalLayout.addWidget(self.create_go_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Input"))
        self.create_tool_button.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "Output"))
        self.label_3.setText(_translate("Dialog", "SqlName"))
        self.create_tool_button_2.setText(_translate("Dialog", "..."))
        self.create_go_button.setText(_translate("Dialog", "Go"))
