# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'standard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Standard(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 53)
        Dialog.setMinimumSize(QtCore.QSize(0, 30))
        Dialog.setStyleSheet("background-color: rgb(216, 225, 229);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.standard_tool = QtWidgets.QToolButton(Dialog)
        self.standard_tool.setMinimumSize(QtCore.QSize(30, 30))
        self.standard_tool.setMaximumSize(QtCore.QSize(30, 30))
        self.standard_tool.setStyleSheet("color: rgb(41, 96, 115);\n"
"background-color: rgb(173, 197, 207);")
        self.standard_tool.setObjectName("standard_tool")
        self.gridLayout.addWidget(self.standard_tool, 0, 3, 1, 1)
        self.standard_button = QtWidgets.QPushButton(Dialog)
        self.standard_button.setMinimumSize(QtCore.QSize(0, 30))
        self.standard_button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.standard_button.setFont(font)
        self.standard_button.setStyleSheet("color: rgb(41, 96, 115);\n"
"background-color: rgb(173, 197, 207);")
        self.standard_button.setObjectName("standard_button")
        self.gridLayout.addWidget(self.standard_button, 0, 4, 1, 1)
        self.standard_line = QtWidgets.QLineEdit(Dialog)
        self.standard_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.standard_line.setFont(font)
        self.standard_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(41, 96, 115);")
        self.standard_line.setObjectName("standard_line")
        self.gridLayout.addWidget(self.standard_line, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(41, 96, 115);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Standard format"))
        self.standard_tool.setText(_translate("Dialog", "..."))
        self.standard_button.setText(_translate("Dialog", "Transform"))
        self.label.setText(_translate("Dialog", "Fasta File"))
